#!/usr/bin/python

import os
import sys
from utils import appscale_tools
from utils.cli import *
from utils.commons import AppScaleToolsException

__author__ = 'hiranya'

if __name__ == '__main__':
  options = [ OPTION_AUTO, OPTION_KEYNAME, OPTION_IPS ]
  parser = get_parser(options)
  (options, args) = parser.parse_args(sys.argv[1:])

  ips_path = None
  keyname = 'appscale'
  auto = False

  if options.ips is None:
    print_usage_and_exit('IP address configuration not specified', parser)
  elif not os.path.exists(options.ips) or not os.path.isfile(options.ips):
    print_usage_and_exit('IP address configuration must be a valid file path', parser)
  else:
    ips_path = options.ips

  if options.keyname is not None:
    keyname = options.keyname

  if options.auto:
    auto = options.auto

  try:
    appscale_tools.add_key_pair(ips_path, keyname, auto)
  except AppScaleToolsException as e:
    print 'Error performing the requested operation:', e.message