#!/usr/bin/python

import sys
from utils import cli, appscale_tools
from utils.commons import AppScaleToolsException

__author__ = 'hiranya'

if __name__ == '__main__':
  options = [
    cli.OPTION_IPS,
    cli.OPTION_MAX_IMAGES,
    cli.OPTION_MIN_IMAGES,
    cli.OPTION_APP_FILE,
    cli.OPTION_DATABASE,
    cli.OPTION_MACHINE,
    cli.OPTION_INSTANCE_TYPE,
    cli.OPTION_KEYNAME,
    cli.OPTION_GROUP,
    cli.OPTION_INFRASTRUCTURE,
    cli.OPTION_REPLICATION,
    cli.OPTION_READ_FACTOR,
    cli.OPTION_WRITE_FACTOR,
    cli.OPTION_APPENGINE,
    cli.OPTION_RESTORE_FROM_TAR,
    cli.OPTION_RESTORE_NEPTUNE_INFO,
    cli.OPTION_SCP
  ]
  parser = cli.get_parser(options)
  (options, args) = parser.parse_args(sys.argv[1:])
  try:
    appscale_tools.run_instances(infrastructure=options.infrastructure,
      machine=options.machine,
      instance_type=options.instance_type,
      min=options.min,
      max=options.max,
      ips=options.ips,
      database=options.database,
      keyname=options.keyname,
      group=options.group,
      scp=options.scp,
      replication=options.replication,
      read_q=options.read_factor,
      write_q=options.write_factor)
  except AppScaleToolsException as e:
    print e.message